
language: node_js
node_js:
  - "7"
install:
  - "yarn prep"
script:
  - "yarn build"
  - "mkdir build"
  - "cp -r dist build/dist"
  - "cp -r lstm build/lstm"
  - "cp index.html build/index.html"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
  local_dir: "build"
